apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: simple-metrics-endpoint
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-metrics-endpoint
  progressDeadlineSeconds: 600
  autoscalerRef:
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    name: simple-metrics-endpoint
  service:
    port: 8080
    targetPort: 8080
    gateways:
    - istio-system/istio-ingressgateway
    trafficPolicy:
      tls:
        mode: DISABLE
    retries:
      attempts: 5
      perTryTimeout: 1s
      retryOn: "gateway-error,connect-failure,refused-stream"
  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    metrics:
    - name: okay-200
      templateRef:
        name: simple-metrics-endpoint-200
        namespace: test
      thresholdRange:
        min: 1
    - name: error-500
      templateRef:
        name: simple-metrics-endpoint-500
        namespace: test
      thresholdRange:
        max: 0
    webhooks:
      - name: load-test
        url: http://flagger-loadtester.test/
        timeout: 5s
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 http://simple-metrics-endpoint:8080/hello"
